# Generated by Django 5.0.1 on 2024-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_productcolor_productimage_productsize_qna_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
